### ISSUE TITLE
I'm having trouble with translation

### ISSUE THREAD

**Issue by Nipodemos** [NermNermNerm/Junimatic#13]
Hello!
I am loving the idea of a more balanced automate mod, it really makes thing more fair and like I earned the right to have that instead of simply let it all be done for me for free.

I'm brazilian and I want to translate this mod to portuguese, but I don't know where the files that I need to translate are.

Your README mentioned that I could just get the `default.json` file and use it as base, but i cannot find that file, I don't know where it is.

The other option was to "use the new language template", but the link associated to it is broken, and I don't know anything about this new language template since I never modded.

Could you help me with that?

**Comment by NermNermNerm** [comment]
I uploaded version 1.3.0 to Nexus a few minutes ago, please fetch that first!

Hi, the readme is out of date, alas.  On Windows, the default.json is usually here:

```C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\Junimatic\i18n\default.json```

In 1.3.0, there's actually a SMAPI log message that will tell you exactly where it is.

However you come across it, copy that to `pt.json` and translate away.  When you're happy it's complete and done right, go ahead and attach it to this issue and I'll integrate it next release.

**Comment by Nipodemos** [comment]
hey, i'm doing the translation, and have a question:
`"dtOYnKDbnP": "Enter the secret woods on a sunny day between 6 and 11pm.",`
this 6 is 6am or 6pm?

**Comment by NermNermNerm** [comment]
6pm

**Comment by Nipodemos** [comment]
Thanks, i've done the translation and tested it, here it is: https://gist.github.com/Nipodemos/3d3150f9d8d6efa1dc5e8ae631ae9f88

**Comment by NermNermNerm** [comment]
Thanks!
