### ISSUE TITLE
Junimos can spawn under machines and become stuck

### ISSUE THREAD

**Issue by Oxdeception** [NermNermNerm/Junimatic#17]
Video below. 

https://github.com/user-attachments/assets/1bcefd90-e0ed-4280-b615-7d54e886ed58

Noticed while trying to determine why this network has stopped functioning. There are still items in the chest that can be loaded into the preserve jars, yet the Junimos have stopped loading.

I had this happen on another network after removing part of it, have similarly reduced the size of this network, and have since saved and restarted the game.

Freeing the trapped Junimo and then changing screens seems to have resolved the issue in this network.

**Comment by NermNermNerm** [comment]
Interesting!  I'll have a look.  My gut feel after looking at this video is that it's because the portal is up against the wall there and perhaps the spawning code doesn't take into account the possibility that the squares around it might be impassible.

**Comment by NermNermNerm** [comment]
I'm pretty sure I found this one and fixed it in 1.5.  The trouble is that the machine was placed on top of flooring, and the code that looks for open squares thought that if a square had a floor tile on it, then that must mean it's an open square, without even looking to see if a machine was there too.
